### ISSUE TITLE
How to install / run with existing bitcoind full node already in place

### ISSUE THREAD

**Issue by quiquee** [CounterpartyXCP/Documentation#119]
There is no explanation on how to run against an existing bitcoin install. I tried to find in the configuration a place where I can avoid launching another bitcoind but I could not find it. 

Any clue would be most welcome.

Thanks

**Comment by unsystemizer** [comment]
There is, it's at the bottom (Reindex section) of https://github.com/CounterpartyXCP/Documentation/blob/master/Installation/bitcoin_core.md (which is "mirrored" somewhere on the project web site as well, I think). 
As the page explains, you need to use the same or newer version of Bitcoin Core addrindex and let it reindex the blockchain.
This is also explained on the community forum, although there are many posts there so it may be hard to find.
