### ISSUE TITLE
Manual installation does not work with the latest Bitcoin version

### ISSUE THREAD

**Issue by xuzhitong** [CounterpartyXCP/Documentation#217]
```Download the latest [Bitcoin Core](https://github.com/bitcoin/bitcoin/releases) and create a bitcoin.conf file```
The current addrindexers cannot support the latest version of Bitcoin (0.28), you need to use version 0.21, please see another issue:
https://github.com/CounterpartyXCP/addrindexrs/issues/28

**Comment by adamkrellenstein** [comment]
Hm, I don't think it's a bitcoind version thing. I've been running with v27.1.0 forever without problems. Unfortunately, AddrIndexRs is unmaintained. It'll be gone in a matter of weeks.

```
bitcoind --version
Bitcoin Core version v27.1.0
Copyright (C) 2009-2024 The Bitcoin Core developers

Please contribute if you find Bitcoin Core useful. Visit
<https://bitcoincore.org/> for further information about the software.
The source code is available from <https://github.com/bitcoin/bitcoin>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>
adam@Adams-MacBook-Pro ~ > 
```
