### ISSUE TITLE
Write a 'Getting Started' or Installation doc

### ISSUE THREAD

**Issue by ivanaszuber** [CounterpartyXCP/Documentation#25]

**Comment by ivanaszuber** [comment]
@rippler do you want to give this a try? Write a page with all the up to date installation instructions?

**Comment by rippler** [comment]
That's a big task - Bitcoin Core, counterparty-lib (with and without counterblockd), Federated Node, Counterparty GUI....  Let's discuss where to begin and how to organize this work.

**Comment by ivanaszuber** [comment]
Sure, didn't realize it was that much work

**Comment by ivanaszuber** [comment]
Also, I believe Federated Node doc is complete ( @robby-dermody ? )

**Comment by rippler** [comment]
Yes, we should attack the problem in phases. 
`counterparty-lib` would be a good start especially since it's new and docs about it aren't plentiful.

**Comment by ivanaszuber** [comment]
ok, great, let's start with that. I'll create a new folder under Tutorials, 'Setup Tutorials' probably best to place it there (together with FN and other install manuals we make)

**Comment by adamkrellenstein** [comment]
I don't know what kind of original docs we need. We should not have separate installation tutorials for each piece of software. The Getting Started guide just needs to say "if you want to do X, use `counterparty-lib`, if Y `counterparty-cli`, etc..

The installation guide for `counterparty-lib`, e.g., should be on the `counterparty-lib` page...

**Comment by ivanaszuber** [comment]
Ok, I agree with that. As long as we have some kind of 'getting started' guide (I mean it will be pretty confusing for people 'where to start' and which component does what) we can/should keep the individual installation doc on the main pages for each component

**Comment by ivanaszuber** [comment]
done
