### ISSUE TITLE
API Docs are Behind

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/Documentation#50]
- [x] document new API calls like get_assets
- [x] as well as the new objects types that can be returned (like assets object)
- [x] mention pubkey parameter
- [x] `get_tx_info`
- [x] `unpack` 

Moved from https://github.com/CounterpartyXCP/counterpartyd/issues/716

**Comment by unsystemizer** [comment]
> by the way the API docs are wrong, the correct request parameter is data_hex, not tx_hex)

From https://counterpartytalk.org/t/checking-unconfirmed-balances-over-json-rpc/1849/3
