### ISSUE TITLE
Add numeric assets to homepage

### ISSUE THREAD

**Issue by goodtaster** [CounterpartyXCP/Documentation#60]
Currently mentions only 0.5 XCP named assets: 

http://counterparty.io/get-started/
http://counterparty.io/why-counterparty/

In the section "create a custom token" (get started), the tutorial doesn't mention numeric assets, and states that asset names can be up to 14 characters long. (It's now 12, I believe.)

Also my proposed wording would be that assets are always free, but having a name is what costs 0.5 XCP.

**Comment by ivanaszuber** [comment]
Done.
