### ISSUE TITLE
windows.md: semi-official site with OpenSSL for Win binaries is dead

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/Documentation#82]
It's been dead for 7 days. 
There's a second semi-official site, http://indy.fulgan.com/SSL/, but the files are zipped and need to be uncompressed and installed manually (may require documentation updates).

List of "semi-official" sites with binary builds can be found at https://www.openssl.org/about/binaries.html

There's an unofficial location with binaries, but I can't tell whether they were copied from SLProWeb.com or built by these guys since slproweb.com is down.
http://code.x2go.org/releases/binary-win32/3rd-party/Win32OpenSSL/?C=M;O=D

**Comment by ivanaszuber** [comment]
Are you referring to this http://slproweb.com/products/Win32OpenSSL.html?

**Comment by rippler** [comment]
Yeah, now they're back. They were down for 7 days straight (or on multiple occasions in recent days, I checked 3-4 times and every time the site was down).
Closing for now.
